version: '2.2'
services:

  php:
    container_name: yii2-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./sites-enabled:/etc/apache2/sites-enabled:delegated
      - ./app:/app:delegated
    build:
      context: ./
      dockerfile: base.Dockerfile
    ports:
      - 80:80
      - 443:443